language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

before_script:
  - git clone -b 1.3.4 git://github.com/phalcon/cphalcon.git --depth=1 && cd cphalcon/build/safe && phpize && ./configure --enable-phalcon && sudo make install
  - cd ../../../ && phpenv config-add ./tests/phalcon.ini
  - composer self-update
  - composer install --dev --prefer-source
  - composer global require "squizlabs/php_codesniffer=*"
  - export PATH=~/.composer/vendor/bin/:$PATH
  - phpenv rehash

script:
  phpunit -v &
  phpcs --standard=PSR2 --extensions=php --ignore=vendor/*,tests/*,cphalcon/* --warning-severity=0 ./

after_script:
  - ./vendor/bin/coveralls -v